// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveTool(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApproveTool'](arg1, arg2, arg3);
}

export function ArchiveHistory(arg1, arg2) {
  return window['go']['app']['App']['ArchiveHistory'](arg1, arg2);
}

export function ArrangeSandbox(arg1) {
  return window['go']['app']['App']['ArrangeSandbox'](arg1);
}

export function CancelArrange() {
  return window['go']['app']['App']['CancelArrange']();
}

export function CancelChat(arg1) {
  return window['go']['app']['App']['CancelChat'](arg1);
}

export function CancelExtract(arg1) {
  return window['go']['app']['App']['CancelExtract'](arg1);
}

export function CancelExtractPattern(arg1) {
  return window['go']['app']['App']['CancelExtractPattern'](arg1);
}

export function Chat(arg1) {
  return window['go']['app']['App']['Chat'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['app']['App']['CheckUpdate'](arg1);
}

export function CompressContext(arg1) {
  return window['go']['app']['App']['CompressContext'](arg1);
}

export function ComputeStyleStats(arg1) {
  return window['go']['app']['App']['ComputeStyleStats'](arg1);
}

export function CopyToDraft(arg1, arg2) {
  return window['go']['app']['App']['CopyToDraft'](arg1, arg2);
}

export function CreateArcNode(arg1, arg2) {
  return window['go']['app']['App']['CreateArcNode'](arg1, arg2);
}

export function CreateChapter(arg1) {
  return window['go']['app']['App']['CreateChapter'](arg1);
}

export function CreateCharacter(arg1, arg2) {
  return window['go']['app']['App']['CreateCharacter'](arg1, arg2);
}

export function CreateLocation(arg1, arg2) {
  return window['go']['app']['App']['CreateLocation'](arg1, arg2);
}

export function CreateNovel(arg1) {
  return window['go']['app']['App']['CreateNovel'](arg1);
}

export function CreatePreference(arg1, arg2) {
  return window['go']['app']['App']['CreatePreference'](arg1, arg2);
}

export function CreateReaderPerspective(arg1, arg2) {
  return window['go']['app']['App']['CreateReaderPerspective'](arg1, arg2);
}

export function CreateSandbox(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateSandbox'](arg1, arg2, arg3);
}

export function CreateSnapshot() {
  return window['go']['app']['App']['CreateSnapshot']();
}

export function CreateStoryArc(arg1, arg2) {
  return window['go']['app']['App']['CreateStoryArc'](arg1, arg2);
}

export function CreateStyleSample(arg1) {
  return window['go']['app']['App']['CreateStyleSample'](arg1);
}

export function CreateTimelineEntry(arg1, arg2) {
  return window['go']['app']['App']['CreateTimelineEntry'](arg1, arg2);
}

export function DeleteArcNode(arg1, arg2) {
  return window['go']['app']['App']['DeleteArcNode'](arg1, arg2);
}

export function DeleteChapter(arg1) {
  return window['go']['app']['App']['DeleteChapter'](arg1);
}

export function DeleteCharacter(arg1, arg2) {
  return window['go']['app']['App']['DeleteCharacter'](arg1, arg2);
}

export function DeleteCover(arg1) {
  return window['go']['app']['App']['DeleteCover'](arg1);
}

export function DeleteLocation(arg1, arg2) {
  return window['go']['app']['App']['DeleteLocation'](arg1, arg2);
}

export function DeleteNovel(arg1) {
  return window['go']['app']['App']['DeleteNovel'](arg1);
}

export function DeletePreference(arg1) {
  return window['go']['app']['App']['DeletePreference'](arg1);
}

export function DeleteReaderPerspective(arg1, arg2) {
  return window['go']['app']['App']['DeleteReaderPerspective'](arg1, arg2);
}

export function DeleteSandbox(arg1, arg2) {
  return window['go']['app']['App']['DeleteSandbox'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function DeleteSetting(arg1, arg2) {
  return window['go']['app']['App']['DeleteSetting'](arg1, arg2);
}

export function DeleteSkill(arg1) {
  return window['go']['app']['App']['DeleteSkill'](arg1);
}

export function DeleteStoryArc(arg1, arg2) {
  return window['go']['app']['App']['DeleteStoryArc'](arg1, arg2);
}

export function DeleteStyle(arg1) {
  return window['go']['app']['App']['DeleteStyle'](arg1);
}

export function DeleteStyleSample(arg1) {
  return window['go']['app']['App']['DeleteStyleSample'](arg1);
}

export function DeleteTimelineEntry(arg1, arg2) {
  return window['go']['app']['App']['DeleteTimelineEntry'](arg1, arg2);
}

export function DeleteVolume(arg1, arg2) {
  return window['go']['app']['App']['DeleteVolume'](arg1, arg2);
}

export function DiscoverModels(arg1, arg2) {
  return window['go']['app']['App']['DiscoverModels'](arg1, arg2);
}

export function DismissUpdate(arg1) {
  return window['go']['app']['App']['DismissUpdate'](arg1);
}

export function DuplicateSkill(arg1) {
  return window['go']['app']['App']['DuplicateSkill'](arg1);
}

export function ExportNovel(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportNovel'](arg1, arg2, arg3);
}

export function ExtractMaterialStyle(arg1) {
  return window['go']['app']['App']['ExtractMaterialStyle'](arg1);
}

export function ExtractPattern(arg1) {
  return window['go']['app']['App']['ExtractPattern'](arg1);
}

export function ExtractStyle(arg1) {
  return window['go']['app']['App']['ExtractStyle'](arg1);
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetArcNodes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetArcNodes'](arg1, arg2, arg3);
}

export function GetChangedFiles(arg1) {
  return window['go']['app']['App']['GetChangedFiles'](arg1);
}

export function GetChapterPlans(arg1) {
  return window['go']['app']['App']['GetChapterPlans'](arg1);
}

export function GetChapters(arg1) {
  return window['go']['app']['App']['GetChapters'](arg1);
}

export function GetCharacterRelations(arg1) {
  return window['go']['app']['App']['GetCharacterRelations'](arg1);
}

export function GetCharacters(arg1) {
  return window['go']['app']['App']['GetCharacters'](arg1);
}

export function GetCommitFileList(arg1, arg2) {
  return window['go']['app']['App']['GetCommitFileList'](arg1, arg2);
}

export function GetCommitLog(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCommitLog'](arg1, arg2, arg3);
}

export function GetContent(arg1, arg2) {
  return window['go']['app']['App']['GetContent'](arg1, arg2);
}

export function GetCurrentChapter(arg1) {
  return window['go']['app']['App']['GetCurrentChapter'](arg1);
}

export function GetEnabledStyle(arg1) {
  return window['go']['app']['App']['GetEnabledStyle'](arg1);
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetLLMConfig() {
  return window['go']['app']['App']['GetLLMConfig']();
}

export function GetLocationRelations(arg1) {
  return window['go']['app']['App']['GetLocationRelations'](arg1);
}

export function GetLocations(arg1) {
  return window['go']['app']['App']['GetLocations'](arg1);
}

export function GetMaxChapterNumber(arg1) {
  return window['go']['app']['App']['GetMaxChapterNumber'](arg1);
}

export function GetModels() {
  return window['go']['app']['App']['GetModels']();
}

export function GetNovels() {
  return window['go']['app']['App']['GetNovels']();
}

export function GetPlatform() {
  return window['go']['app']['App']['GetPlatform']();
}

export function GetPreferences(arg1) {
  return window['go']['app']['App']['GetPreferences'](arg1);
}

export function GetReaderPerspectives(arg1) {
  return window['go']['app']['App']['GetReaderPerspectives'](arg1);
}

export function GetSandbox(arg1, arg2) {
  return window['go']['app']['App']['GetSandbox'](arg1, arg2);
}

export function GetSession(arg1) {
  return window['go']['app']['App']['GetSession'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['app']['App']['GetSessionMessages'](arg1);
}

export function GetSessions(arg1) {
  return window['go']['app']['App']['GetSessions'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStoryArcs(arg1) {
  return window['go']['app']['App']['GetStoryArcs'](arg1);
}

export function GetStyleContent(arg1) {
  return window['go']['app']['App']['GetStyleContent'](arg1);
}

export function GetStyleSample(arg1) {
  return window['go']['app']['App']['GetStyleSample'](arg1);
}

export function GetTimelineEntries(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTimelineEntries'](arg1, arg2, arg3);
}

export function GetTrashItemContent(arg1) {
  return window['go']['app']['App']['GetTrashItemContent'](arg1);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function GetVolumes(arg1) {
  return window['go']['app']['App']['GetVolumes'](arg1);
}

export function GetWritingActivity(arg1) {
  return window['go']['app']['App']['GetWritingActivity'](arg1);
}

export function GetWritingStats() {
  return window['go']['app']['App']['GetWritingStats']();
}

export function ImportDraft(arg1, arg2) {
  return window['go']['app']['App']['ImportDraft'](arg1, arg2);
}

export function ImportNovel(arg1) {
  return window['go']['app']['App']['ImportNovel'](arg1);
}

export function ImportWithLLM(arg1) {
  return window['go']['app']['App']['ImportWithLLM'](arg1);
}

export function Initialize(arg1) {
  return window['go']['app']['App']['Initialize'](arg1);
}

export function InstallSkill(arg1) {
  return window['go']['app']['App']['InstallSkill'](arg1);
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function ListHistory(arg1, arg2) {
  return window['go']['app']['App']['ListHistory'](arg1, arg2);
}

export function ListSandboxHistory(arg1, arg2) {
  return window['go']['app']['App']['ListSandboxHistory'](arg1, arg2);
}

export function ListSandboxes(arg1) {
  return window['go']['app']['App']['ListSandboxes'](arg1);
}

export function ListSettings(arg1) {
  return window['go']['app']['App']['ListSettings'](arg1);
}

export function ListSkillLibrary() {
  return window['go']['app']['App']['ListSkillLibrary']();
}

export function ListSkills(arg1) {
  return window['go']['app']['App']['ListSkills'](arg1);
}

export function ListSlashCommands(arg1) {
  return window['go']['app']['App']['ListSlashCommands'](arg1);
}

export function ListSnapshotFiles(arg1) {
  return window['go']['app']['App']['ListSnapshotFiles'](arg1);
}

export function ListSnapshots() {
  return window['go']['app']['App']['ListSnapshots']();
}

export function ListStyleSamples(arg1) {
  return window['go']['app']['App']['ListStyleSamples'](arg1);
}

export function ListStyles() {
  return window['go']['app']['App']['ListStyles']();
}

export function ListTrashItems(arg1) {
  return window['go']['app']['App']['ListTrashItems'](arg1);
}

export function LogFrontend(arg1) {
  return window['go']['app']['App']['LogFrontend'](arg1);
}

export function NormalizeVolumeOrders(arg1, arg2) {
  return window['go']['app']['App']['NormalizeVolumeOrders'](arg1, arg2);
}

export function PickAndImportNovel(arg1) {
  return window['go']['app']['App']['PickAndImportNovel'](arg1);
}

export function PickDataDir() {
  return window['go']['app']['App']['PickDataDir']();
}

export function PurgeTrashItem(arg1) {
  return window['go']['app']['App']['PurgeTrashItem'](arg1);
}

export function RebuildNovelIndex(arg1) {
  return window['go']['app']['App']['RebuildNovelIndex'](arg1);
}

export function RecomputePrevChapters(arg1) {
  return window['go']['app']['App']['RecomputePrevChapters'](arg1);
}

export function RenameSkill(arg1) {
  return window['go']['app']['App']['RenameSkill'](arg1);
}

export function RenameVolume(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameVolume'](arg1, arg2, arg3);
}

export function ReorderChapter(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ReorderChapter'](arg1, arg2, arg3, arg4);
}

export function ReorderChaptersBatch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ReorderChaptersBatch'](arg1, arg2, arg3, arg4);
}

export function ReorderVolumes(arg1, arg2) {
  return window['go']['app']['App']['ReorderVolumes'](arg1, arg2);
}

export function RestoreHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['RestoreHistory'](arg1, arg2, arg3);
}

export function RestoreSandboxHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['RestoreSandboxHistory'](arg1, arg2, arg3);
}

export function RestoreSnapshotAll(arg1) {
  return window['go']['app']['App']['RestoreSnapshotAll'](arg1);
}

export function RestoreSnapshotFile(arg1) {
  return window['go']['app']['App']['RestoreSnapshotFile'](arg1);
}

export function RestoreTrashItem(arg1) {
  return window['go']['app']['App']['RestoreTrashItem'](arg1);
}

export function SaveArchiveInterval(arg1) {
  return window['go']['app']['App']['SaveArchiveInterval'](arg1);
}

export function SaveAvatar(arg1) {
  return window['go']['app']['App']['SaveAvatar'](arg1);
}

export function SaveContent(arg1) {
  return window['go']['app']['App']['SaveContent'](arg1);
}

export function SaveCover(arg1, arg2) {
  return window['go']['app']['App']['SaveCover'](arg1, arg2);
}

export function SaveGitConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveGitConfig'](arg1, arg2);
}

export function SaveHistoryLimit(arg1) {
  return window['go']['app']['App']['SaveHistoryLimit'](arg1);
}

export function SaveLLMConfig(arg1) {
  return window['go']['app']['App']['SaveLLMConfig'](arg1);
}

export function SaveMaintainReminderMinutes(arg1) {
  return window['go']['app']['App']['SaveMaintainReminderMinutes'](arg1);
}

export function SaveSandbox(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveSandbox'](arg1, arg2, arg3);
}

export function SaveSetting(arg1) {
  return window['go']['app']['App']['SaveSetting'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveStyleToLibrary(arg1, arg2) {
  return window['go']['app']['App']['SaveStyleToLibrary'](arg1, arg2);
}

export function SaveUserName(arg1) {
  return window['go']['app']['App']['SaveUserName'](arg1);
}

export function SaveVolumes(arg1, arg2) {
  return window['go']['app']['App']['SaveVolumes'](arg1, arg2);
}

export function SearchAll(arg1, arg2) {
  return window['go']['app']['App']['SearchAll'](arg1, arg2);
}

export function SelectMaterialFile() {
  return window['go']['app']['App']['SelectMaterialFile']();
}

export function SetActiveNovel(arg1) {
  return window['go']['app']['App']['SetActiveNovel'](arg1);
}

export function SetApprovalMode(arg1) {
  return window['go']['app']['App']['SetApprovalMode'](arg1);
}

export function SetCurrentChapter(arg1, arg2) {
  return window['go']['app']['App']['SetCurrentChapter'](arg1, arg2);
}

export function SetDataDir(arg1) {
  return window['go']['app']['App']['SetDataDir'](arg1);
}

export function SetEnabledStyle(arg1, arg2) {
  return window['go']['app']['App']['SetEnabledStyle'](arg1, arg2);
}

export function SetLastSession(arg1) {
  return window['go']['app']['App']['SetLastSession'](arg1);
}

export function SetReasoningEffort(arg1) {
  return window['go']['app']['App']['SetReasoningEffort'](arg1);
}

export function SetSelectedModel(arg1, arg2) {
  return window['go']['app']['App']['SetSelectedModel'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function UpdateArcNode(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateArcNode'](arg1, arg2, arg3);
}

export function UpdateChapterPlan(arg1, arg2) {
  return window['go']['app']['App']['UpdateChapterPlan'](arg1, arg2);
}

export function UpdateChapterTitle(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateChapterTitle'](arg1, arg2, arg3);
}

export function UpdateCharacter(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateCharacter'](arg1, arg2, arg3);
}

export function UpdateDataDir(arg1) {
  return window['go']['app']['App']['UpdateDataDir'](arg1);
}

export function UpdateLocation(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateLocation'](arg1, arg2, arg3);
}

export function UpdateNovel(arg1, arg2) {
  return window['go']['app']['App']['UpdateNovel'](arg1, arg2);
}

export function UpdatePreference(arg1, arg2) {
  return window['go']['app']['App']['UpdatePreference'](arg1, arg2);
}

export function UpdateReaderPerspective(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateReaderPerspective'](arg1, arg2, arg3);
}

export function UpdateSandboxMeta(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateSandboxMeta'](arg1, arg2, arg3, arg4);
}

export function UpdateStoryArc(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateStoryArc'](arg1, arg2, arg3);
}

export function UpdateStyleSample(arg1) {
  return window['go']['app']['App']['UpdateStyleSample'](arg1);
}

export function UpdateTimelineEntry(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateTimelineEntry'](arg1, arg2, arg3);
}
